services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=webapp'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

    expose:
      - '5432'
